# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c47ec7a7-773c-4f08-a198-e627871eb361";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/90E4-5ECC";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ed85b47a-e911-45eb-a7d7-762b6e42ac26";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/83edeb22-ae8c-4e81-ae89-d166e9cfef0c"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
